# Generated by Django 3.1 on 2020-08-11 19:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_url', models.CharField(max_length=2048, unique=True)),
                ('title', models.CharField(max_length=1024)),
                ('image', models.CharField(max_length=2048)),
                ('likes', models.CharField(max_length=20)),
                ('responses', models.CharField(max_length=20)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048), size=None)),
                ('creator', models.CharField(max_length=100)),
                ('creator_image', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('image', models.CharField(max_length=2048)),
                ('likes', models.CharField(max_length=20)),
                ('responses', models.CharField(max_length=20)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048), size=None)),
                ('paragraph', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('creator', models.CharField(max_length=100)),
                ('creator_image', models.CharField(max_length=2048)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_scraper.article')),
            ],
        ),
    ]
