# Generated by Django 3.1 on 2020-08-11 19:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper', '0003_auto_20200811_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
    ]
