# Generated by Django 3.1 on 2020-08-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper', '0005_auto_20200811_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
